[package]
name = "datalog-reporter"
version = "0.1.0"
authors = ["Charlie Wilkin <charlie@busyboredom.com>"]
edition = "2018"

[dependencies]
tiberius = "0"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0", features = ["compat"] }
anyhow = "1"
printpdf = "0"